name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu-latest' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libxdo-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Build Rust module
        working-directory: ./bluebird
        run: |
          maturin build --release --strip --interpreter python

      - name: Install built bluebird wheel
        working-directory: ./bluebird
        shell: bash
        run: |
          wheel=$(ls target/wheels/*.whl | head -n 1)
          pip install "$wheel" --force-reinstall

      - name: Run PyInstaller
        shell: bash
        run: |
          pyinstaller \
            --add-data "theme:theme" \
            --add-data "resources:resources" \
            --name liz-desktop \
            --onefile \
            --windowed \
            --icon "resources\icon_1024.png" \
            --clean \
            main.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: liz-desktop-${{ matrix.os }}
          path: |
            dist/
            !dist/*.spec
