name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install python dependencies
        run: pip install maturin pynput pyinstaller rapidfuzz PySide6 notify-py python-dotenv

      - name: Build Rust module
        working-directory: ./bluebird
        run: |
          maturin build --release --interpreter python
          pip install target/wheels/bluebird-*.whl --force-reinstall

      - name: Run PyInstaller (Linux)
        run: |
          pyinstaller \
            --add-data "theme:theme" \
            --add-data "resources:resources" \
            --name Liz-desktop \
            --onefile \
            --windowed \
            --clean \
            main.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Liz-desktop-${{ matrix.os }}
          path: |
            dist/
            !dist/*.spec
