name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu  # For Linux
          # For Windows, it will automatically detect the target

      - name: Install Rust (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustup

      - name: Install Maturin
        run: pip install maturin

      - name: Build Rust module
        working-directory: ./bluebird
        run: |
          maturin build --release --interpreter python
          pip install target/wheels/bluebird-*.whl --force-reinstall

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PySide6 pyinstaller

      - name: Run PyInstaller (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller \
            --add-data "theme:theme" \
            --add-data "resources:resources" \
            --name Liz-desktop \
            --onefile \
            --windowed \
            --clean \
            main.py

      - name: Run PyInstaller (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller `
            --add-data "theme;theme" `
            --add-data "resources;resources" `
            --name Liz-desktop `
            --onefile `
            --windowed `
            --clean `
            main.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Liz-desktop-${{ matrix.os }}
          path: |
            dist/
            !dist/*.spec
